### PR TITLE
First draft of the GDPR guide

### PR DESCRIPTION
**Pull request by JoshuaSimpson**
This has a checklist for organisers, as well as a more in depth explanation of each key part of the GDPR

### CODE REVIEW

**Comment by jonmarkgo** [comment]
Why would we need permission to link to a third party resource? I don't think we included any of their content...

**Comment by nquinlan** [comment]
This looks excellent. I need to add some language to it about us not being lawyers and our lawyer is updating the privacy policy, but then I'll merge. Thanks for your patience.

**Comment by chibnguyen** [comment]
@nquinlan to confirm, has our legal team looked at this already?

**Comment by nquinlan** [comment]
Yes and no. They've had a cursory look, but I'm getting a review by a GDPR expert, the privacy policy needs major updates though.

**Comment by imabp** [comment]
Is this still active? 
Need some insights :)

**Pull request closed without merging**
