### PR TITLE
Add Quill

### PR DESCRIPTION
**Pull request by anishathalye**
cc @jlin816

### CODE REVIEW

**Comment by jlin816** [comment]
@Shy @jonmarkgo Just wanted to check in on this PR -- it's a simple addition but it'll be helping a lot of hackathon organizers! Let us know if you need more info from us.

**Comment by anishathalye** [comment]
Ping. Is there any reason this hasn't been merged, while other PRs have been merged [[1](https://github.com/MLH/mlh-hackathon-organizer-guide/pull/50)] and commits have been made [[2](https://github.com/MLH/mlh-hackathon-organizer-guide/commits/master)]?

Are there any changes that need to be made to this PR before it can be merged?

**Comment by theycallmeswift** [comment]
Hey @anishathalye and @jlin816! Thanks so much for submitting this and sorry for the delay getting back to you here. Taking this long to respond to your request (or at least let you we are working on it) is not at the standard of excellence that I expect from the MLH team and know we are capable of.  

We're currently heads down getting ready for next season and I know that updating the guide is part of that.  I'll make sure that someone on our team gets assigned to this request and responds to you within the next week or so.  Thanks for your patience and sorry again for the delay!

**Comment by anishathalye** [comment]
Awesome, thanks!

**Comment by Shy** [comment]
Hey @anishathalye, sorry on my slow response to this. I've been thinking a lot about the policies around what software we should allow into the guide. Unlike some of the other tools you've posted I haven't had an experience with Quill so I don't have any idea if it's something that we can suggest to people as a possible best practices software for registration.

**Comment by jlin816** [comment]
Thanks for the response @Shy!

Quill has just recently been open-sourced, so I wouldn't expect a super extensive list of previous users -- but that's exactly why we're looking to put this in the MLH guide. Hopefully more hackathons can benefit from this in the future.

We actually presented Quill along with our other open-source software at Hackcon last year (it was still a work-in-progress then), and a lot of organizers were really excited about how it would help their hackathons. Here are some hackathons that expressed interest at Hackcon and wanted to see the private beta version before it was even open sourced:
- bitcamp
- HackGT
- TreeHacks
- Uncommon Hacks (UChicago)
- Hack the North
- HackPrinceton
- BoilerMake
- HackKean
- DesertHacks
- HackCWRU

I asked our friends over at HackGT about their experience with Quill:
> Quill was a great tool for HackGT. It had an organized and straightforward codebase that made it easy to get started and adapt to our usage. Any developers familiar with the MEAN stack and MVC can get up and running extremely quickly. HackGT was able to extend the API to add addition features and even build a separate client-only application in a matter of weeks. I also helped ConUHacks get set up with Quill and I think they had a good experience with it.

**Comment by Shy** [comment]
@jlin816 thanks for providing the write up. Hearing that another event has successfully used it and had a good experience with it makes me comfortable merging this in.

**Pull request merged**
