### PR TITLE
Add more software for hackathons

### PR DESCRIPTION
**Pull request by AlbertSuarez**
After organizing some hackathons and developing some cool software, it would be awesome if some other hackathons will be using them.

Looking forward to its approvance.

Thanks :smile:

### CODE REVIEW

**Comment by AlbertSuarez** [comment]
Hey @mlh-henry! 👋 Hope you are doing well. Does this repo be maintained? Would be interesting to merge this PR in my option since there are a lot of cool software for hackathons nowadays.

**Comment by mlh-henry** [comment]
thank you for your contributions! this repo is led by @chibnguyen. She can take a look at your PR and see if its appropriate to merge

**Comment by AlbertSuarez** [comment]
Hey @chibnguyen! Did you have the opportunity to see and review this PR? Thanks 😊

**Comment by AlbertSuarez** [comment]
Any update @chibnguyen ?

**Comment by nlaz** [comment]
Hey @AlbertSuarez sorry for the delay. I just joined recently and I should be able to help out here. Would it be possible to update the Mentors repository to include more documentation about how to use the project? Organizers should be able to know from the documentation how it works and how to set it up. The HackAssistant project you included would be a very good example.

**Comment by AlbertSuarez** [comment]
Completely agree with you, @nlaz. Mentors repository is not well documented and we don't have the resource to document it properly to be honested. With that being said, I've edited the PR removing the Mentors app but leaving the HackAssistant one. Hope this is enough for accepting it. Thanks 😄

**Comment by nlaz** [comment]
@AlbertSuarez Totally understood. I've been there with projects before. Thanks for updating the PR. I will merge it now. 🙌

**Pull request merged**
